services:
  accountmanager:
    build: .
    container_name: "accountmanager"
    ports:
      - 8080:8080
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017
    command: ["--bind_ip","0.0.0.0"]
